manager_repuestos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

def home_redirect(request):
    return redirect("pedidos:listar")



urlpatterns = [
    # Página de inicio y login/logout bajo "sesiones"
    path("", include(("sesiones.urls", "sesiones"), namespace="sesiones")),

    path("admin/", admin.site.urls),

    # Usuarios
    path("usuarios/",include(("usuarios.urls", "usuarios"), namespace="usuarios")),

    # Clientes
    path("clientes/",include(("clientes.urls", "clientes"), namespace="clientes")),

    # Repuestos
    path("repuestos/",include(("repuestos.urls", "repuestos"), namespace="repuestos")),

    # Pedidos
    path("pedidos/",include(("pedidos.urls", "pedidos"), namespace="pedidos")),

    path("", home_redirect, name="inicio"),





]

pedidos/urls.py
from django.urls import path
from . import views
from . import api

app_name = "pedidos"

urlpatterns = [
    # Página principal
    path("", views.listar_pedidos, name="inicio"),
    path("listar/", views.listar_pedidos, name="listar"),

    # Crear nuevo pedido (selección de cliente)
    path("nuevo/", views.nuevo_pedido_cliente, name="nuevo_cliente"),
    
    # CRUD pedido
    path("editar/<int:id>/", views.editar_pedido, name="editar"),
    path("confirmar_division/<int:id>/", views.confirmar_division, name="confirmar_division"),
    path("cancelar/<int:id>/", views.cancelar_pedido, name="cancelar"),
    path("actualizar_estado/<int:id>/", views.actualizar_estado, name="actualizar_estado"),
    # Ítems del pedido
    path("<int:pedido_id>/items/", views.agregar_items, name="agregar_items"),
    path("buscar_equipo/", views.buscar_equipo, name="buscar_equipo"),


    # APIs AJAX — Modo NS, Equipo, Descripción
    path("api/consultar_ns/", api.api_consultar_ns, name="api_consultar_ns"),
    
    # API REAL — Buscar equipos (para modo B)
    path("api/buscar_equipos/", api.api_buscar_equipos, name="api_buscar_equipos"),
    
    # APIs de clientes
    path("api/buscar_clientes/", api.api_buscar_clientes, name="api_buscar_clientes"),
    path("api/lista_materiales/", api.api_lista_materiales_equipo, name="api_lista_materiales_equipo"),
    path("api/buscar_materiales/", api.api_buscar_materiales, name="api_buscar_materiales"),
    path("api/agregar_item/", api.api_agregar_item, name="api_agregar_item"),
]

sesiones/urls.py
from django.urls import path, reverse_lazy
from .views import login_view, logout_view, inicio
from django.contrib.auth import views as auth_views

app_name = "sesiones"

urlpatterns = [
    path("", inicio, name="inicio"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset_form.html',
            email_template_name='registration/password_reset_email.html',
            success_url=reverse_lazy('sesiones:password_reset_done'),
        ),
        name='password_reset'
    ),
    path(
        'password_reset_done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url=reverse_lazy('sesiones:password_reset_complete'),
        ),    
        name='password_reset_confirm'
    ),
    path(
        'reset_done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
    <meta charset="UTF-8">
    <div class="logo">
            Manager de Repuestos
            <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}"/>
    </div>


    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <style>
        body {
            margin: 0;
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
        }

        .navbar {
            background-color: #343a40;
        }

        .navbar-brand,
        .nav-link {
            color: white !important;
        }

        .nav-link:hover {
            color: #ccc !important;
        }

        .contenido {
            padding: 20px;
        }
    </style>
</head>

<body>

<!-- NAVBAR PRINCIPAL -->
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'sesiones:inicio' %}">Manager Repuestos</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">

            <!-- MENÚ IZQUIERDO -->
            <ul class="navbar-nav me-auto">

                <!-- SUBMENÚ PEDIDOS -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="pedidosDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Pedidos
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="pedidosDropdown">
                        <li><a class="dropdown-item" href="{% url 'pedidos:nuevo_cliente' %}">Nuevo</a></li>
                        <li><a class="dropdown-item" href="{% url 'pedidos:listar' %}">Listar</a></li>
                    </ul>
                </li>

                <!-- MENÚ REPUESTOS -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'repuestos:listar' %}">Repuestos</a>
                </li>

                <!-- SOLO GERENTE O ADMINISTRADOR -->
                {% if request.user.is_authenticated %}
                    {% if request.user.rol == 'admin' or request.user.rol == 'gerente' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuarios:listar' %}">Usuarios</a>
                        </li>
                    {% endif %}
                {% endif %}


            </ul>

            <!-- MENÚ DERECHO (LOGIN / LOGOUT) -->
            <ul class="navbar-nav">

                {% if request.user.is_authenticated %}
                    <li class="navbar-text ms-auto">
                        Usuario: {{ request.user.username }}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sesiones:logout' %}">Cerrar sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sesiones:login' %}">Iniciar sesión</a>
                    </li>
                {% endif %}

            </ul>

        </div>
    </div>
</nav>


<!-- CONTENIDO -->
<div class="contenido container">
    {% block contenido %}
    {% endblock %}
</div>

</body>
</html>

templates/inicio.html
{% extends "base.html" %}

{% block contenido %}
<h1>Bienvenido</h1>

<p>Usuario logueado: {{ request.user.username }}</p>

<p><a href="{% url 'sesiones:logout' %}">Cerrar sesión</a></p>
{% endblock %}